<?php

require_once 'gcaba_establecimientos_educativos_webservices.class.php';

// METODOS DEL HOOK

/**
 * Implements gcaba_establecimientos_educativos_init().
 */
function gcaba_establecimientos_educativos_init(){
    // Chequeamos si estamos en el módulo
    if( !empty($_GET['q']) && stristr($GLOBALS['_GET']['q'], 'buscador-de-establecimientos-educativos') !== false ){
        $parametros = explode('/', $_GET['q']);

        // Chequeamos si existe algún "parámetro" seteado en la URL (nombre de un establecimiento), lo guardamos y redireccionamos a la página original del módulo
        if( count($parametros) > 1 ){
            $_SESSION['parametros'] = $parametros;
            drupal_goto($GLOBALS['base_url'].'/buscador-de-establecimientos-educativos');
        }
    }
}

//function gcaba_establecimientos_educativos_init() {}
function gcaba_hook_js_alter(&$javascript) {
    $javascript['misc/jquery.js']['data'] = drupal_get_path('module', 'gcaba_establecimientos_educativos') . '/jquery-3.3.1.min.js'; // Swap out jQuery to use an updated version of the library
}

/**
 * Implements hook_menu().
 */
function gcaba_establecimientos_educativos_menu()
{
    $items = array();

//    if( !in_array('admin', arg()) ){ var_dump(arg()); die; }

//    $items['buscador-de-establecimientos-educativos/'.$url_arg[1]] = array(
//        'page callback' => 'gcaba_establecimientos_educativos_block_view',
//        'page arguments' => array('callback_parametros'),
//        'access arguments' => array('access content'),
//        'type' => MENU_NORMAL_ITEM
//    );

    $items['admin/config/gcaba_configurations/gcaba_establecimientos_educativos/configuraciones'] = array(
        'title' => t('Establecimientos Educativos'),
        'description' => t('Campos configurables para la consulta de Establecimientos Educativos.'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('gcaba_establecimientos_educativos_configuraciones'),
        'access callback' => 'user_access',
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM
    );


    return $items;
}


/**
 * Implementa hook_block_info().
 */
function gcaba_establecimientos_educativos_block_info()
{
    $blocks['viewEstablecimientosEducativos'] = array(
        'info' => t('EstablecimientosEducativos'),
        'status'	=> FALSE,
        'cache' => DRUPAL_NO_CACHE
    );

    return $blocks;
}

/**
 * Implementa hook_view().
 */
function gcaba_establecimientos_educativos_block_view($delta = '') {

    $block = array();

    if($delta == 'viewEstablecimientosEducativos') {
        $block['content'] = drupal_get_form('gcaba_establecimientos_educativos_form');
        unset($_SESSION['parametros']);
    }

    return $block;
}


// METODOS DEL FORMULARIO
/**
 * Genera el formulario con las preguntas de la encuesta
 */
function gcaba_establecimientos_educativos_form($form, &$form_state)
{

    gcaba_hook_js_alter();

    // --------------- DIVS ID CAMPOS BUSQUEDA API ----------------- //
    /*
       Estas variables representan los ids de los contenedores html,
       que a su vez se utilizan como los criterios de búsqueda hacia la API de establecimientos,
       por lo tanto, deben coincidir con el nombre del campo definido en el archivo "v1.0.0-rc.6.raml"
    */

    $id_gestion = 'gestion_id';
    $id_ofertas = 'oferta_id';
    $id_titulo = 'titulo_id';
    $id_orientacion = 'orientacion_id';
    $id_jornada = 'jornada_id';
    $id_sala = 'sala_id';
    $id_criterio_busqueda = 'criterio_busqueda_id';
    $id_barrio = 'barrio_id';
    $id_comuna = 'comuna_id';
    $id_distrito_escolar = 'distrito_escolar_id';
    $id_dependencia_funcional = 'dependencia_funcional_id';
    $id_tipo_establecimiento = 'tipo_establecimiento_id';
    $id_palabra_clave = 'palabra_clave';
    $id_ubicacion = 'ubicacion_id';
    // ------------------------------------------------------------- //


    $form['busqueda_alumno'] = array(
        '#type' => 'container',
        '#id' => 'busqueda_alumno',
        '#attributes' => array('class' => array('hidden')),
    );

    $form['busqueda_escuela'] = array(
        '#type' => 'container',
        '#id' => 'busqueda_escuela'
    );

    // ---------------- GESTION ----------------- //
    $radio_gestion = array(1 => 'Estatal', 2 => 'Privada', 3 => 'Ambas');

    $form['busqueda_alumno']['gestion'] = array(
        '#prefix' => '<div class="row row-mbot-1 criterio"><div class="col-md-12"><label>Gestión</label>',
        '#suffix' => '</div></div>',
        '#id' => $id_gestion,
    );
    $form['busqueda_alumno']['gestion']['radios'] = array(
        '#prefix' => '<div class="row">',
        '#type' => 'radios',
        '#default_value' => 3,
        '#options' => $radio_gestion,
        '#suffix' => '</div>',
    );


    // ---------------- OFERTAS ----------------- //
    $ofertas = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$oferta);

    $options_ofertas = array('Todas');

    foreach ($ofertas as $oferta) {
        $options_ofertas[$oferta['id']] = $oferta['nombre'];
    }

    $form['busqueda_alumno']['ofertas'] = array(
        '#prefix' => '<div class="row row-mbot-1 criterio"><div class="col-md-12">',
        '#type' => 'select',
        '#title' => t('Ofertas'),
        '#default_value' => 0,
        '#options' => $options_ofertas,
        '#suffix' => '</div></div>',
        '#id' => $id_ofertas
    );


    // ---------------- TITULOS ----------------- //
    $titulos = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$titulo);

    $options_titulos = array('Todos');
    foreach ($titulos as $titulo) {
        $options_titulos[$titulo['id']] = $titulo['nombre'];
    }

    $form['busqueda_alumno']['titulos'] = array(
        '#prefix' => '<div class="row row-mbot-1 criterio"><div class="col-md-12">',
        '#type' => 'select',
        '#title' => t('Títulos'),
        '#default_value' => 0,
        '#options' => $options_titulos,
        '#suffix' => '</div></div>',
        '#id' => $id_titulo,
    );


    // ---------------- ORIENTACIONES ----------------- //
    $orientaciones = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$orientacion);

    $options_orientaciones = array('Todas');
    foreach ($orientaciones as $orientacion) {
        $options_orientaciones[$orientacion['id']] = $orientacion['nombre'];
    }

    $form['busqueda_alumno']['orientaciones'] = array(
        '#prefix' => '<div class="row row-mbot-1 criterio"><div class="col-md-12">',
        '#type' => 'select',
        '#title' => t('Orientaciones'),
        '#default_value' => 0,
        '#options' => $options_orientaciones,
        '#suffix' => '</div></div>',
        '#id' => $id_orientacion,
    );


    // ---------------- JORNADAS ----------------- //
    $jornadas = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$jornada);

    $options_jornadas = array('Todas');
    foreach ($jornadas as $jornada) {
        $options_jornadas[$jornada['id']] = $jornada['nombre'];
    }

    $form['busqueda_alumno']['jornadas'] = array(
        '#prefix' => '<div class="row row-mbot-1 criterio"><div class="col-md-12">',
        '#type' => 'select',
        '#title' => t('Jornadas'),
        '#default_value' => 0,
        '#options' => $options_jornadas,
        '#suffix' => '</div>',
        '#id' => $id_jornada,
    );


    // ---------------- SALAS ----------------- //
    $salas = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$sala);

    $options_salas = array('Todas');
    foreach ($salas as $sala) {
        $options_salas[$sala['id']] = $sala['nombre'];
    }

    $form['busqueda_alumno']['salas'] = array(
        '#prefix' => '<div class="col-md-6">',
        '#type' => 'select',
        '#title' => t('Salas'),
        '#default_value' => 0,
        '#options' => $options_salas,
        '#suffix' => '</div></div>',
        '#id' => $id_sala,
    );


    // ----------------- CRITERIO DE BUSQUEDA ----------------- //
    $form['busqueda_alumno']['criterio_busqueda'] = array(
        '#prefix' => '<div class="row row-mbot-1" style="display: none;"><div class="col-md-12">',
        '#type' => 'radios',
        '#title' => t('Buscar por'),
        '#default_value' => 0,
        '#options' => array(t('Barrio/Comnuna/D.E.'), t('Dirección de tu casa o cercanía')),
        '#suffix' => '</div></div>',
        '#id' => $id_criterio_busqueda
    );

    // ----------------- BUSQUEDA POR UBICACION ----------------- //
    $form['busqueda_alumno']['ubicacion'] = array(
//        '#prefix' => '<div class="row row-mbot-1 criterio" style="background-color: #e5e5e5ad; height: 7em; padding: 1em; width: 100%; margin-left: auto; margin-right: auto; display: none;"><div class="col-md-12">',
        '#prefix' => '<div class="row row-mbot-1 criterio" style="display: none;"><div class="col-md-12">',
        '#type' => 'textfield',
        '#title' => t('Buscar por dirección de tu casa o cercanía'),
        '#suffix' => '</div></div>',
        '#id' => $id_ubicacion,
        '#attributes' => array(
            'class' => array('has-button'),
            'placeholder' => 'Dirección (calle y altura o cruce de calles)'
        ),
    );

    // ---------------- BARRIO ----------------- //
    $barrios = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$barrios);

    // -------- REORDENAMIENTO DE BARRIOS ALFABETICAMENTE --------------- //
    // Obtener una lista de columnas
    $barrios_asc = array();
    foreach ($barrios as $clave => $fila) {
        $barrios_asc[$clave] = $fila['nombre'];
    }

    array_multisort($barrios_asc, SORT_ASC, $barrios);
    // ------------------------------------------------------------------ //

    $options_barrios = array('Todos');

    foreach ($barrios as $barrio) {
        $options_barrios[$barrio['id'] . '_' . $barrio['comunaId']] = $barrio['nombre'];
    }

    $form['busqueda_alumno']['barrio'] = array(
        '#prefix' => '<div class="row row-mbot-1 criterio">
                                    <div class="col-md-6">',
        '#type' => 'select',
        '#title' => t('Barrio'),
        '#default_value' => 0,
        '#options' => $options_barrios,
        '#suffix' => '</div>',
        '#id' => $id_barrio
    );


    // ---------------- COMUNA ----------------- //
    $comunas = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$comunas);

    $options_comuna = array('Todas');
    foreach ($comunas as $comuna) {
        $options_comuna[$comuna['id']] = $comuna['nombre'];
    }

    $form['busqueda_alumno']['comuna'] = array(
        '#prefix' => '<div class="col-md-3">',
        '#type' => 'select',
        '#title' => t('Comuna'),
        '#default_value' => 0,
        '#options' => $options_comuna,
        '#suffix' => '</div>',
        '#id' => $id_comuna
    );


    // ---------------- D.E. ----------------- //
    $distritos = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$distrito);

    $options_de = array('Todos');
    foreach ($distritos as $distrito) {
        $options_de[$distrito['id']] = $distrito['nombre'];
    }

    $form['busqueda_alumno']['de'] = array(
        '#prefix' => '    <div class="col-md-3">',
        '#type' => 'select',
        '#title' => t('Distrito Escolar'),
        '#default_value' => 0,
        '#options' => $options_de,
        '#suffix' => '    </div>
                                </div>',
        '#id' => $id_distrito_escolar
    );


    // ---------------- DEPENDENCIA FUNCIONAL ----------------- //
    $dependencias = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$dependencia);

    $options_dep_func = array('Desconozco');
    foreach ($dependencias as $dependencia) {
        $options_dep_func[$dependencia['id']] = $dependencia['nombre'];
    }

    $form['busqueda_alumno']['dependencia_funcional'] = array(
        '#prefix' => '<div class="row row-mbot-1 criterio">
                        <div class="col-md-6 col-xs-6">',
        '#type' => 'select',
        '#title' => t('Dependencia Funcional'),
        '#default_value' => 0,
        '#options' => $options_dep_func,
        '#suffix' => '  </div>',
        '#id' => $id_dependencia_funcional
    );


    // ---------------- TIPO DE ESTABLECIMIENTO ----------------- //
    $establecimientos = establecimientos_web_services::getAPIestablecimientos(establecimientos_web_services::$establecimiento);

    $options_tipo_est = array('Desconozco');
    foreach ($establecimientos as $establecimiento) {
        if ($establecimiento['nombre'] !== 'No corresponde') {
            $options_tipo_est[$establecimiento['id'] . '_' . $establecimiento['dependenciaFuncionalId']] = $establecimiento['nombre'];
        }
    }

    $form['busqueda_alumno']['tipo_establecimiento'] = array(
        '#prefix' => '    <div class="col-md-6 col-xs-6">',
        '#type' => 'select',
        '#title' => t('Tipo de Establecimiento'),
        '#default_value' => 0,
        '#options' => $options_tipo_est,
        '#suffix' => '    </div>
                      </div>',
        '#id' => $id_tipo_establecimiento
    );


    // ---------------- PALABRAS CLAVE ----------------- //
    $form['busqueda_alumno']['palabras_clave'] = array(
        '#prefix' => '<div class="row row-mbot-1 criterio"><div class="col-md-12">',
        '#type' => 'textfield',
        '#title' => t('Palabras clave: (nombre, dirección, CUE)'),
        '#suffix' => '</div></div>',
        '#id' => $id_palabra_clave
    );


    // BOTON BUSCAR
    $form['busqueda_alumno']['botones']['buscar'] = array(
        '#prefix' => '<div class="row row-mbot-3"><div class="text-center col-md-12 boton">',
        '#type' => 'button',
        '#value' => t('Buscar'),
        '#attributes' => array(
            'class' => array('btn btn-xl btn-primary'),
        ),
        '#suffix' => '</div></div>',
    );


    // ----------------- SECCION RESULTADOS BUSQUEDA -------------- //

    $form['busqueda_alumno']['resultados'] = array(
        '#type' => 'container',
        '#prefix' => '<div id="resultados">',
        '#suffix' => '</div>',
    );


    $form['busqueda_alumno']['resultados']['cantidad'] = array(
        '#markup' => '<div class="row"><div class="col-md-12 contenedor-form-l"><p style="float: left;"><strong style="margin-right: 0.3em;">' . t('Resultados de búsqueda:') . '</strong></p> <p style="float: left;" id="cant_resultados"></p></div></div>
                      <div class="row area_impresion"><div class="col-md-12 contenedor-form-l row-mbot-1"><p id="criterios_busqueda"><strong style="margin-right: 1.2em">' . t('Criterios de búsqueda:') . '</strong> </p></div></div>',
    );

    $form['busqueda_alumno']['resultados']['botones'] = array('#markup' => '<div class="row">
                                    <div class="col-md-offset-10 col-md-2 col-sm-offset-8 col-sm-4">
                                       <div id="boton_mapa"  class="btn btn-default">Mapa</div>
                                          <div id="boton_lista" class="btn btn-default boton_activo">Lista</div>
                                                  </div>
                                     </div>'
    );

    $form['busqueda_alumno']['resultados']['mapa'] = dibujarHTMLMapaResultados();
    $form['busqueda_alumno']['resultados']['tabla']['resultados'] = dibujarHTMLTablaResultados();
    $form['busqueda_alumno']['resultados']['tabla']['paginacion'] = dibujarHTMLPaginacionResultados();

    // BOTON IMPRIMIR
    $form['busqueda_alumno']['resultados']['imprimir'] = array(
        '#prefix' => '<div class="row row-mbot-3 imprimir_descargar">
                       <div class="text-center col-md-4 col-md-offset-2 boton imprimir">',
        '#type' => 'button',
        '#value' => t('Imprimir'),
        '#attributes' => array(
            'class' => array('btn btn-xl btn-primary'),
        ),
        '#suffix' => '    </div>',
    );

    $form['modal'] = array(
        '#prefix' => '<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                              <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        <div class="container-fluid">
                                        <h3></h3>
                                        <i class="fa fa-spinner" style="font-size:48px;color:red"></i>',
        '#suffix' => '</div>
                                    </div>
                                </div>
                              </div>
                        </div>'
    );

    // BOTON DESCARGAR
    $form['busqueda_alumno']['resultados']['descargar'] = array(
        '#prefix' => '    <div class="text-center col-md-4 boton descargar">',
        '#type' => 'button',
        '#value' => t('Descargar'),
        '#attributes' => array(
            'class' => array('btn btn-xl btn-primary'),
            'disabled' => 'disabled',
        ),
        '#suffix' => '</div></div>',
    );


    $form['final'] = array(
        '#type' => 'container',
        '#id' => 'final'
    );

    $form['final']['descarga_correcta'] = array(
        '#markup' => '<div class="row row-mbot-2"><div class="col-md-12 text-center"> <h3>El archivo fue descargado correctamente.</h3> </div></div>',
    );

    // BOTON NUEVA BUSQUEDA
    $form['final']['nueva_busqueda'] = array(
        '#prefix' => '<div class="row row-mbot-2 final"><hr> <div class="text-center col-md-12 boton">',
        '#type' => 'button',
        '#value' => t('Realizar nueva búsqueda'),
        '#attributes' => array(
            'class' => array('btn btn-xl btn-primary nueva_busqueda'),
        ),
        '#suffix' => '</div></div>',
    );


    $path_modulo = drupal_get_path('module', 'gcaba_establecimientos_educativos');
    $url_usig = variable_get('gcaba_establecimientos_url_mapa_usig');

    drupal_add_js($path_modulo . '/js/gcaba_establecimientos_educativos.js');
    drupal_add_js($path_modulo . '/js/lib/xlsx.full.min.js');
    drupal_add_js($path_modulo . '/js/lib/FileSaver.js');
    drupal_add_js($path_modulo . '/js/lib/jquery.simplePagination.js');
    drupal_add_js($path_modulo . '/js/lib/MapaInteractivo.min.js');
    drupal_add_js($path_modulo . '/js/lib/proj4.js');

    // Mapas Usig
//    drupal_add_js($url_usig.'usig.MapaInteractivo.min.js');
//    drupal_add_js($url_usig.'usig.MapaEstatico.min.js');
    drupal_add_js($url_usig . 'usig.Punto.min.js');
    drupal_add_js($url_usig . 'usig.AutoCompleterFull.min.js');

    // Estilos
    drupal_add_css($path_modulo . '/css/gcaba_establecimientos_educativos.css');


    // -------------- GUARDADO PERMANENTE DE ICONOS EN BD -------------------- //
    // Sin el siguiente proceso, los archivos subidos en la configuración del módulo se eliminan automáticamente en la ejecución del cron
//    $icono_estatal = file_load(variable_get('gcaba_establecimientos_icono_estatales'));
//    $icono_privado = file_load(variable_get('gcaba_establecimientos_icono_privados'));

//    $icono_estatal->status = 0;
//    file_save($icono_estatal);h

//    $icono_privado->status = 0;
//    file_save($icono_privado);
    // ------------------------------------------------------------------------ //


    // Agregamos variables para ser accedidas desde el js
    drupal_add_js(array('gcaba_establecimientos_educativos' => array('php_url_api_establecimientos' => establecimientos_web_services::$url_web_service)), array('type' => 'setting'));
    drupal_add_js(array('gcaba_establecimientos_educativos' => array('php_url_mapa_usig'            => $url_usig)), array('type' => 'setting'));
    drupal_add_js(array('gcaba_establecimientos_educativos' => array('php_parametros_get'           => $_SESSION['parametros'])), array('type' => 'setting'));
    drupal_add_js(array('gcaba_establecimientos_educativos' => array('icono_estatal'            => $path_modulo.'/img/estatales.png')), array('type' => 'setting'));
    drupal_add_js(array('gcaba_establecimientos_educativos' => array('icono_privado'            => $path_modulo.'/img/privados.png')), array('type' => 'setting'));

    // Divs Ids criterios de busqueda API
    drupal_add_js(array('gcaba_establecimientos_educativos' => array(
        'id_gestion'               => $id_gestion,
        'id_ofertas'               => $id_ofertas,
        'id_titulo'                => $id_titulo,
        'id_orientacion'           => $id_orientacion,
        'id_jornada'               => $id_jornada,
        'id_sala'                  => $id_sala,
        'id_barrio'                => $id_barrio,
        'id_comuna'                => $id_comuna,
        'id_distrito_escolar'      => $id_distrito_escolar,
        'id_dependencia_funcional' => $id_dependencia_funcional,
        'id_tipo_establecimiento'  => $id_tipo_establecimiento,
        'id_palabra_clave'         => $id_palabra_clave,
        'id_ubicacion'             => $id_ubicacion,
        'id_criterio_busqueda'     => $id_criterio_busqueda,
    )
    ), array('type' => 'setting'));
    //---------------------------------------------------

    return $form;
}

function dibujarHTMLMapaResultados(){
    $resultado_busqueda = array(
        '#prefix' => '<div class="row area_impresion" id="contenedor_mapa" style="width: 100%; margin: 0 0 5em 0;"><div class="col-md-12">',
        '#markup' => '<div id="resultados_mapa"></div>',
        '#suffix' => '</div></div>'
    );

    return $resultado_busqueda;
}

function dibujarHTMLTablaResultados(){
    $resultado_busqueda = array(
        '#prefix' => '<div class="row area_impresion"><div class="col-md-12">',
        '#markup' => '<table class="table" id="tabla_resultados">
                            <thead>
                                <tr class="header_table">
                                    <th class="col-md-1">'.t('Gestión').'</th>
                                    <th class="col-md-3">'.t('Tipo de establecimiento').'</th>
                                    <th class="col-md-4">'.t('Nombre').'</th>
                                    <th class="col-md-2">'.t('Dirección').'</th>
                                    <th class="col-md-2">'.t('Barrio').'</th>
                                </tr>
                            </thead>
                            
                            <tbody>
                            </tbody>
                      </table>',
        '#suffix' => '</div></div>'
    );

    return $resultado_busqueda;
}

function dibujarHTMLPaginacionResultados(){
    $paginacion_resultados = array(
        '#prefix' => '<div class="row text-center"><div class="col-md-12">',
        '#markup' => ' <ul class="pagination"></ul>',
        '#suffix' => '</div></div>'
    );

    return $paginacion_resultados;
}


// CONFIGURACIONES DEL MODULO

function gcaba_establecimientos_educativos_configuraciones()
{
    $form['gcaba_establecimientos_url_web_service'] = array(
        '#type'          => 'textfield',
        '#title'         => t('Url de API de Establecimientos'),
        '#description'   => t('Url central de donde se obtendran los servicios requeridos para el módulo.'),
        '#default_value' => variable_get('gcaba_establecimientos_url_web_service'),
    );

    $form['gcaba_establecimientos_url_mapa_usig'] = array(
        '#type'          => 'textfield',
        '#title'         => t('Url de mapas USIG'),
        '#description'   => t('Url de donde se obtiene el la localización de cada establecimiento en el mapa de usig.'),
        '#default_value' => variable_get('gcaba_establecimientos_url_mapa_usig'),
    );

//  $form['gcaba_establecimientos_icono_estatales'] = array(
//    '#type'          => 'managed_file',
//    '#title'         => t('Icono para establecimientos estatales'),
//    '#default_value' => variable_get('gcaba_establecimientos_icono_estatales'),
//    '#upload_location' => 'public://uploads/',
//  );
//
//  $form['gcaba_establecimientos_icono_privados'] = array(
//    '#type'          => 'managed_file',
//    '#title'         => t('Icono para establecimientos privados'),
//    '#default_value' => variable_get('gcaba_establecimientos_icono_privados'),
//    '#upload_location' => 'public://uploads/',
//  );

//    $form['#submit'][] = 'gcaba_establecimientos_educativos_configuraciones_form_submit';

    return system_settings_form($form);
}


function gcaba_establecimientos_educativos_configuraciones_form_submit($form, &$form_state) {
    $archivo_estatales = $form['gcaba_establecimientos_icono_estatales']['#file'];
    $archivo_privados  = $form['gcaba_establecimientos_icono_privados']['#file'];

    if( $archivo_estatales ){
        $icono_estatales = file_load($archivo_estatales->fid);
        $icono_estatales->status = FILE_STATUS_PERMANENT;
        file_save($icono_estatales);

        file_usage_add($icono_estatales, 'gcaba_establecimientos_educativos', 'iconos_estatales', $archivo_estatales->fid);
    }
    if( $archivo_privados ){
        $icono_privados = file_load($archivo_privados->fid);
        $icono_privados->status = FILE_STATUS_PERMANENT;
        file_save($icono_privados);

        file_usage_add($icono_privados, 'gcaba_establecimientos_educativos', 'iconos_privados', $archivo_privados->fid);
    }
}


